--Create tables for SRC level

 CREATE TABLE SRC_CUSTOMERS ( 
   ID  NUMBER(10),  
   NAME  VARCHAR2(50),  
   USERNAME  VARCHAR2(50),  
   EMAIL  VARCHAR2(50),  
   DATEOFBIRTH  DATE,  
   STREETADDRESS  VARCHAR2(100),  
   CITY  VARCHAR2(30),  
   COUNTRY  VARCHAR2(30),  
   ZIP  VARCHAR2(6),  
   STATE  VARCHAR2(2),  
   PHONE  VARCHAR2(50)
 );


 CREATE TABLE  SRC_PAYMENTS  ( 
   PAYMENTID  NUMBER(10),  
   CUSTOMERID  NUMBER(10),  
   PRODUCTID  NUMBER(10),  
   TRANSACTIONDATE  DATE,  
   CREDITCARD  VARCHAR2(20),  
   CREDITCARDNUMBER  VARCHAR2(20)
 );
 
CREATE TABLE  SRC_PRODUCTS  ( 
  PRODUCTS  NUMBER(10),  
  PRODUCTNAME  VARCHAR2(100),  
  COMPANYNAME  VARCHAR2(100),  
  PRICE  FLOAT(126),  
  WAREHOUSELOCATIONSTATE  VARCHAR2(2)
);


--Create tables for CLS level
 CREATE TABLE CLS_CUSTOMERS (
   ID_SURR  NUMBER (10),
   ID  NUMBER(10),
	 NAME  VARCHAR2(50 BYTE), 
	 USERNAME  VARCHAR2(50 BYTE), 
	 EMAIL  VARCHAR2(50 BYTE), 
	 DATEOFBIRTH  DATE, 
	 STREETADDRESS  VARCHAR2(100 BYTE), 
	 CITY  VARCHAR2(30 BYTE), 
	 COUNTRY  VARCHAR2(30 BYTE), 
	 ZIP  VARCHAR2(6 BYTE), 
	 STATE  VARCHAR2(2 BYTE), 
	 PHONE  VARCHAR2(50 BYTE));
   


CREATE TABLE  CLS_PRODUCTS  (
  ID_SURR  NUMBER (10),
  ID  NUMBER(10),   
  PRODUCTNAME  VARCHAR2(100),  
  COMPANYNAME  VARCHAR2(100),  
  PRICE  FLOAT(126),  
  WAREHOUSELOCATIONSTATE  VARCHAR2(2)
); 


 CREATE TABLE  CLS_PAYMENTS  ( 
   PAYMENTID  NUMBER(10),  
   CUSTOMER_ID_SURR  NUMBER(10),  
   PRODUCT_ID_SURR  NUMBER(10),  
   TRANSACTIONDATE  DATE,  
   CREDITCARD  VARCHAR2(20),  
   CREDITCARDNUMBER  VARCHAR2(20),
   ISINTERSTATE NUMBER(2)
 );
 
 
--Create tables for DIM level
 CREATE TABLE DIM_CUSTOMERS (
   ID_SURR  NUMBER (10),
   ID  NUMBER(10),
	 NAME  VARCHAR2(50 BYTE), 
	 USERNAME  VARCHAR2(50 BYTE), 
	 EMAIL  VARCHAR2(50 BYTE), 
	 DATEOFBIRTH  DATE, 
	 STREETADDRESS  VARCHAR2(100 BYTE), 
	 CITY  VARCHAR2(30 BYTE), 
	 COUNTRY  VARCHAR2(30 BYTE), 
	 ZIP  VARCHAR2(6 BYTE), 
	 STATE  VARCHAR2(2 BYTE), 
	 PHONE  VARCHAR2(50 BYTE));
   
CREATE SEQUENCE DM_CUSTOMERS_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;



 CREATE TABLE  FCT_PAYMENTS  ( 
   PAYMENTID  NUMBER(10),  
   CUSTOMER_ID_SURR  NUMBER(10),  
   PRODUCT_ID_SURR  NUMBER(10),  
   TRANSACTIONDATE  DATE,  
   CREDITCARD  VARCHAR2(20),  
   CREDITCARDNUMBER  VARCHAR2(20),
   ISINTERSTATE NUMBER(2)
 );
 

CREATE TABLE  DIM_PRODUCTS  (
  ID_SURR  NUMBER (10),
  ID  NUMBER(10),   
  PRODUCTNAME  VARCHAR2(100),  
  COMPANYNAME  VARCHAR2(100),  
  PRICE  FLOAT(126),  
  WAREHOUSELOCATIONSTATE  VARCHAR2(2)
); 

CREATE SEQUENCE DM_PRODUCTS_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;


